# Generated by Django 3.2.21 on 2024-08-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=30, unique=True)),
                ('age', models.IntegerField(default=18)),
                ('sex', models.BooleanField(default=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('salary', models.FloatField(default=10000.455)),
                ('money', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
