# Generated by Django 3.2.21 on 2024-08-25 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='user',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
