# Generated by Django 3.2.21 on 2024-08-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20240825_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='icon',
            field=models.FileField(null=True, upload_to='static/uploads'),
        ),
        migrations.AddField(
            model_name='user',
            name='icon2',
            field=models.ImageField(null=True, upload_to='static/uploads'),
        ),
    ]
