# Generated by Django 3.2.21 on 2024-08-31 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
